# @see https://docs.docker.com/compose/compose-file/
version: '3.9'
services:
  nginx:
    container_name: nginx
    image : nginx:1.25-alpine
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
      - ./static:/example/static:ro